apiVersion: v1
kind: PersistentVolume
metadata:
  name: httpd-fileserver
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  nfs:
    path: /data
    server: 192.168.0.5

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: httpd-fileserver
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  volumeName: httpd-fileserver
  resources:
    requests:
      storage: 2Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: httpd-app
  name: httpd-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: httpd-app
  template:
    metadata:
      labels:
        app: httpd-app
    spec:
      volumes:
      - name: httpd-fileserver
        persistentVolumeClaim:
          claimName: httpd-fileserver # same name of pvc that was created
      containers:
      - image: httpd:latest
        name: httpd-app
        ports:
        - containerPort: 80
          name: httpd-app
        volumeMounts:
        - name: httpd-fileserver # name of volume should match claimName volume
          mountPath: /usr/local/apache2/htdocs/ # mount inside of contianer